/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mls;

import java.awt.Color;
import java.text.DecimalFormat;
import java.util.LinkedList;
import java.util.PriorityQueue;
import java.util.Queue;
import java.util.Stack;
import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;
import mls.generatori.Generatore3Erlangiano;
import mls.generatori.GeneratoreEsponenziale;
import mls.generatori.GeneratorePoissoniano;
import mls.generatori.GeneratoreUniforme;
import mls.util.Clona;
import mls.util.Coda;
import mls.util.CodaFIFO;
import mls.util.CodaLIFO;
import mls.util.CodaSPTF;
import mls.util.EventoComparator;
import mls.util.Generatore;
import mls.util.JobComparator;
import mls.util.StatoCorrente;
import mls.util.TipoEvento;

/**
 *
 * @author Michele Milidoni <michelemilidoni@gmail.com>
 */
public class FrameWin extends javax.swing.JFrame {

    private PriorityQueue<Evento> calendario;
    private Coda<Job> cpuQueue;
    private Coda<Job> ioQueue;

    private Generatore genArrivi;
    private Generatore genCentri;
    private GeneratoreUniforme genUni;
    private Job jobCorrenteCpu;
    private Job jobCorrenteIO;
    private int p;
    private int n0, nRun = 0, nOss = 0;
    private double uSommaG[];
    private double en[];
    private double vc[];
    private double x[];
    private double y[];
    private double uSommaStat;
    private boolean stopSequenziatore = false;
    private boolean stabile = false;
    private boolean convalida = false;

    private Coda<Job> cpuQueueStabile;
    private Coda<Job> ioQueueStabile;
    private PriorityQueue<Evento> calendarioStabile;
    private Job jobCorrenteCpuStabile;
    private Job jobCorrenteIOStabile;

    private final DecimalFormat df;
    private String testoOut = "";
    private boolean fineSimulazione = false;

    private StatoCorrente[] statiCorrenti;
    
    private final Semaphore semaforo;

    /**
     * Creates new form FrameWin
     */
    public FrameWin() {
        initComponents();
        buttonAvvia.setEnabled(true);
        buttonStabile.setEnabled(false);
        df = new DecimalFormat("#.####");
        semaforo = new Semaphore(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        textGamma = new javax.swing.JFormattedTextField();
        buttonAvvia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textP = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        textTs = new javax.swing.JFormattedTextField();
        buttonAvvia1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textOutput = new javax.swing.JTextPane();
        jSeparator2 = new javax.swing.JSeparator();
        framePlot1 = new mls.FramePlot();
        buttonStabile = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        textPuntoCentrale = new javax.swing.JTextField();
        textLimiteSuperiore = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textLimiteInferiore = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        textGeneratoreCentri = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textCodaCPU = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textGeneratoreArrivi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textCodaIO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Milidoni MLS Parte2");
        setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Sistema simulato");

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/michele/NetBeansProjects/MLS_Milidoni_Finale/src/main/java/mls/schema2.jpg")); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        textGamma.setText("30");

        buttonAvvia.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        buttonAvvia.setText("Simula");
        buttonAvvia.setToolTipText("");
        buttonAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAvviaActionPerformed(evt);
            }
        });

        jLabel4.setText("Gamma");

        jLabel6.setText("Run di stab. (p)");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Configurazione");

        textP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        textP.setText("30");
        textP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPActionPerformed(evt);
            }
        });

        jLabel5.setText("Ts");

        textTs.setText("0.5");
        textTs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTsActionPerformed(evt);
            }
        });

        buttonAvvia1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        buttonAvvia1.setText("Convalida");
        buttonAvvia1.setToolTipText("");
        buttonAvvia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAvvia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonAvvia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textGamma)
                    .addComponent(textTs)
                    .addComponent(textP)
                    .addComponent(buttonAvvia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textGamma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textTs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAvvia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAvvia1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Log");

        textOutput.setEditable(false);
        textOutput.setFont(new java.awt.Font("Andale Mono", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(textOutput);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        buttonStabile.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        buttonStabile.setText("SISTEMA STABILE");
        buttonStabile.setToolTipText("");
        buttonStabile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStabileActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Grafici");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        textPuntoCentrale.setEditable(false);

        textLimiteSuperiore.setEditable(false);

        jLabel13.setText("Punto centrale:");

        jLabel15.setText("Limite superiore:");

        jLabel14.setText("Limite inferiore:");

        textLimiteInferiore.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPuntoCentrale, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(textLimiteInferiore)
                    .addComponent(textLimiteSuperiore))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textPuntoCentrale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(textLimiteInferiore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(textLimiteSuperiore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textGeneratoreCentri.setEditable(false);

        jLabel10.setText("Tipo generatore centri:");

        jLabel12.setText("Tipo coda I/O:");

        textCodaCPU.setEditable(false);

        jLabel11.setText("Tipo coda CPU:");

        textGeneratoreArrivi.setEditable(false);

        jLabel9.setText("Tipo generatore arrivi:");

        textCodaIO.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textGeneratoreArrivi, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(textGeneratoreCentri)
                    .addComponent(textCodaCPU)
                    .addComponent(textCodaIO))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textGeneratoreArrivi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textGeneratoreCentri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textCodaCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textCodaIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(buttonStabile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(framePlot1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(framePlot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStabile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStabileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStabileActionPerformed
        try {
            semaforo.acquire();
            setStabile();
            buttonAvvia.setEnabled(false);
            buttonStabile.setEnabled(false);
            buttonStabile.setText("CALCOLO INTERVALLO DI CONFIDENZA IN CORSO");
            semaforo.release();
        } catch (InterruptedException ex) {
            Logger.getLogger(FrameWin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonStabileActionPerformed

    private void buttonAvvia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAvvia1ActionPerformed
        convalida = true;
        SwingWorker worker = new SwingWorker<Boolean, Void>() {
            @Override
            protected Boolean doInBackground() throws Exception {
                avviaSimulazione(Integer.parseInt(textP.getText()),
                        Double.parseDouble(textGamma.getText()),
                        Double.parseDouble(textTs.getText()));
                return true;
            }
        };

        buttonAvvia.setEnabled(false);
        buttonStabile.setEnabled(true);
        worker.execute();
    }//GEN-LAST:event_buttonAvvia1ActionPerformed

    private void textTsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTsActionPerformed

    private void textPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPActionPerformed

    private void buttonAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAvviaActionPerformed

        convalida = false;
        SwingWorker worker = new SwingWorker<Boolean, Void>() {
            @Override
            protected Boolean doInBackground() throws Exception {
                avviaSimulazione(Integer.parseInt(textP.getText()),
                        Double.parseDouble(textGamma.getText()),
                        Double.parseDouble(textTs.getText()));
                return true;
            }
        };

        buttonAvvia.setEnabled(false);
        buttonStabile.setEnabled(true);
        worker.execute();
    }//GEN-LAST:event_buttonAvviaActionPerformed

    public void avviaSimulazione(int p, double gamma, double mu) {
        statoIniziale();
        nRun = 0;
        nOss = 0;
        textLimiteInferiore.setText("");
        textLimiteSuperiore.setText("");
        textPuntoCentrale.setText("");

        textOutput.setText("");
        testoOut = "---------------- INIZIO SIMULAZIONE ---------------- \n";
        int nMax = 10000;
        genUni = new GeneratoreUniforme();
        if (convalida) {
            genArrivi = new GeneratorePoissoniano(gamma, genUni);
            genCentri = new GeneratoreEsponenziale(mu, genUni);
        } else {
            genArrivi = new GeneratoreEsponenziale(gamma, genUni);
            double ts3 = mu / 3;
            genCentri = new Generatore3Erlangiano(mu, new GeneratoreUniforme());
        }

        textGeneratoreArrivi.setText(genArrivi.getClass().getName());
        textGeneratoreCentri.setText(genCentri.getClass().getName());
        textCodaCPU.setText(cpuQueue.getClass().getName());
        textCodaIO.setText(ioQueue.getClass().getName());

        en = new double[nMax];
        vc = new double[nMax];
        fineSimulazione = false;
        nRun = 0;
        nOss = 0;
        stabile = false;
        stopSequenziatore = false;

        this.p = p;
        uSommaG = new double[p];
        statiCorrenti = new StatoCorrente[p];
        testoOut += " ---> fase stabilizzazione con " + p + " run <--- \n";
        framePlot1.resetSerieMedia();
        framePlot1.resetSerieVarianza();
        for (int n = 1; n <= nMax && !fineSimulazione; n++) {
            setN0(n);
            sequenziatore();
        }
    }

    private void statoIniziale() {
        if (convalida) {
            cpuQueue = new CodaFIFO<>();
            ioQueue = new CodaFIFO<>();
        } else {
            cpuQueue = new CodaSPTF<>(new JobComparator());
            ioQueue = new CodaLIFO<>();
        }

        calendario = new PriorityQueue<>(new EventoComparator());
        jobCorrenteCpu = null;
        jobCorrenteIO = null;
    }

    private void statoEquilibrio() {
        if (convalida) {
            cpuQueue = Clona.fifoQueue((CodaFIFO<Job>) cpuQueueStabile);
            ioQueue = Clona.fifoQueue((CodaFIFO<Job>) ioQueueStabile);
        } else {
            cpuQueue = Clona.sptfQueue((CodaSPTF<Job>) cpuQueueStabile);
            ioQueue = Clona.lifoQueue((CodaLIFO<Job>) ioQueueStabile);
        }
        calendario = Clona.calendario(calendarioStabile);
        if (jobCorrenteCpuStabile != null) {
            jobCorrenteCpu = jobCorrenteCpuStabile.clona();
            jobCorrenteCpuStabile = null;
        }
        if (jobCorrenteIOStabile != null) {
            jobCorrenteIO = jobCorrenteIOStabile.clona();
            jobCorrenteIOStabile = null;
        }
        uSommaStat = 0d;
        setN0(genUni.next(50, 100));
        nOss = 0;
    }

    private void setStatoEquilibrio() {
        testoOut += " ---> fase statistica con n0 = " + n0 + " <--- \n";
        x = new double[p];
        y = new double[p];
        if (convalida) {
            cpuQueueStabile = Clona.fifoQueue((CodaFIFO<Job>) cpuQueue);
            ioQueueStabile = Clona.fifoQueue((CodaFIFO<Job>) ioQueue);
        } else {
            cpuQueueStabile = Clona.sptfQueue((CodaSPTF<Job>) cpuQueue);
            ioQueueStabile = Clona.lifoQueue((CodaLIFO<Job>) ioQueue);
        }
        System.out.println(calendario.size());
        calendarioStabile = Clona.calendario(calendario);
        if (jobCorrenteCpu != null) {
            jobCorrenteCpuStabile = jobCorrenteCpu.clona();
            jobCorrenteCpu = null;
        }
        if (jobCorrenteIO != null) {
            jobCorrenteIOStabile = jobCorrenteIO.clona();
            jobCorrenteIO = null;
        }
    }

    public void setN0(int n0) {
        this.n0 = n0;
        stopSequenziatore = false;
//        System.out.println("imposto n0 = " + n0);
    }

    private void sequenziatore() {
        while (!stopSequenziatore) {
            if (nRun == p) {
                calendario.add(new Evento(0d, TipoEvento.FINE_SIMULAZIONE));
            }
            calendario.add(new Evento(genArrivi.next(), TipoEvento.ARRIVO));
            Evento e = calendario.poll();
            if (null != e.getTipo()) {
                switch (e.getTipo()) {
                    case ARRIVO:
                        arrivo();
                        break;
                    case FINE_CPU:
                        fineCPU();
                        break;
                    case FINE_IO:
                        fineIO();
                        break;
                    case FINE_SIMULAZIONE:
                        fineSimulazione();
                        break;
                    default:
                        break;
                }
            }
        }
    }

    private void arrivo() {
        Job job = new Job();
        job.setCaricoCorrente(genCentri.next());
        //System.out.println(" ARRIVO ");
        //System.out.println(job);

        if (jobCorrenteCpu == null) {
            jobCorrenteCpu = job;
            calendario.add(new Evento(job.getCaricoCorrente(), TipoEvento.FINE_CPU));
            //System.out.println("imposto jobCorrenteCpu");
        } else {
            cpuQueue.metti(job);
            //System.out.println("metto il job in sptfQueue");
        }
    }

    private void fineCPU() {
        double routing = genUni.next();
        if (routing <= 0.9) {
            if (jobCorrenteIO == null) {
                jobCorrenteIO = (Job) jobCorrenteCpu.clona();
                jobCorrenteIO.setCaricoCorrente(genCentri.next());
                calendario.add(new Evento(jobCorrenteIO.getCaricoCorrente(), TipoEvento.FINE_IO));
                //System.out.println("imposto jobCorrenteIO da CPU");
            } else {
                Job temp = jobCorrenteCpu.clona();
                temp.setCaricoCorrente(genCentri.next());
                ioQueue.metti(temp);
                //System.out.println("metto il job in lifoQueue");
            }

        } else if (!stabile) {
            try {
                semaforo.acquire();
            } catch (InterruptedException ex) {
                Logger.getLogger(FrameWin.class.getName()).log(Level.SEVERE, null, ex);
            }
            uSommaG[nRun++] += jobCorrenteCpu.getCaricoTotale();

            if (nRun == p) {
                testoOut += "  Osservazioni: " + n0 + "\n";

                double temp = 0;
                for (int jj = 0; jj < p; jj++) {
                    temp += uSommaG[jj] / n0;
                }
                en[n0 - 1] = temp / p;
                testoOut += "   Media campionaria e(" + n0 + "): " + df.format(en[n0 - 1]) + "\n";

                double temp2 = 0;
                for (int jj = 0; jj < p; jj++) {
                    temp2 += Math.pow(uSommaG[jj] / n0 - en[n0 - 1], 2);
                }
                vc[n0 - 1] = temp2 / (p - 1);
                testoOut += "   Varianza campionaria s(" + n0 + "): " + df.format(vc[n0 - 1]) + "\n";

                framePlot1.addSerieMedia(n0 - 1, en[n0 - 1]);
                framePlot1.addSerieVarianza(n0 - 1, vc[n0 - 1]);

                nRun = 0;
                stopSequenziatore = true;
            }
            if (n0 == 1) {
                statoIniziale();
            }
            semaforo.release();

        } else {
            uSommaStat += jobCorrenteCpu.getCaricoTotale();
            nOss++;

            if (nOss == n0) {
                y[nRun] = n0;
                x[nRun] = uSommaStat;
                nRun++;
                stopSequenziatore = true;
                statoEquilibrio();
            }

            if (nRun == p) {
                calendario.add(new Evento(0d, TipoEvento.FINE_SIMULAZIONE));
            }
        }

        jobCorrenteCpu = null;

        if (!cpuQueue.isEmpty()) {
            jobCorrenteCpu = (Job) cpuQueue.togli();
            jobCorrenteCpu.setCaricoCorrente(genCentri.next());
            calendario.add(new Evento(jobCorrenteCpu.getCaricoCorrente(), TipoEvento.FINE_CPU));
            //System.out.println("prelevo un job da cpuQueue " + cpuQueue.size());
        }
    }

    private void fineIO() {
        if (jobCorrenteCpu == null) {
            jobCorrenteCpu = (Job) jobCorrenteIO.clona();
            jobCorrenteCpu.setCaricoCorrente(genCentri.next());
            calendario.add(new Evento(jobCorrenteCpu.getCaricoCorrente(), TipoEvento.FINE_CPU));
            //System.out.println("imposto jobCorrenteCpu da IO");
        } else {
            Job temp = jobCorrenteIO.clona();
            temp.setCaricoCorrente(genCentri.next());
            cpuQueue.metti(temp);
            //System.out.println("metto il job in sptfQueue");
        }
        jobCorrenteIO = null;

        if (!ioQueue.isEmpty()) {
            jobCorrenteIO = (Job) ioQueue.togli();
            jobCorrenteIO.setCaricoCorrente(genCentri.next());
            calendario.add(new Evento(jobCorrenteIO.getCaricoCorrente(), TipoEvento.FINE_IO));
            //System.out.println("prelevo un job da ioQueue");
        }
    }

    private void fineSimulazione() {
        double xSegn = 0;
        double ySegn = 0;
        for (int jj = 0; jj < p; jj++) {
            xSegn += x[jj];
            ySegn += y[jj];
        }
        xSegn /= p;
        ySegn /= p;

        double xSommaQDiff = 0;
        double ySommaQDiff = 0;
        double xySommaQDiff = 0;
        for (int jj = 0; jj < p; jj++) {
            xSommaQDiff += Math.pow(x[jj] - xSegn, 2);
            ySommaQDiff += Math.pow(y[jj] - ySegn, 2);
            xySommaQDiff += (x[jj] - xSegn) * (y[jj] - ySegn);
        }

        double s2_11 = xSommaQDiff / (p - 1);
        double s2_22 = ySommaQDiff / (p - 1);
        double s2_12 = xySommaQDiff / (p - 1);

        double f = xSegn / ySegn;
        double s2 = s2_11 - 2 * f * s2_12 + f * f * s2_22;
        double d = Math.sqrt(s2) / (ySegn * Math.sqrt(p));
        double mediaInferiore = f - d * 1.645;
        double mediaSuperiore = f + d * 1.645;

        framePlot1.addMarker(f, Color.GREEN);
        framePlot1.addMarker(mediaInferiore, Color.RED);
        framePlot1.addMarker(mediaSuperiore, Color.RED);
        testoOut += "Punto centrale: " + df.format(f) + " \nIntervallo di confidenza (u1, u2): (" + df.format(mediaInferiore) + ", " + df.format(mediaSuperiore) + ")\n";
        testoOut += "----------------  FINE SIMULAZIONE  ---------------- \n";
        textOutput.setText(testoOut);
        textLimiteInferiore.setText(df.format(mediaInferiore));
        textLimiteSuperiore.setText(df.format(mediaSuperiore));
        textPuntoCentrale.setText(df.format(f));

        buttonAvvia.setEnabled(true);
        buttonStabile.setEnabled(false);
        buttonStabile.setText("SISTEMA STABILE");
        stopSequenziatore = true;
        fineSimulazione = true;
    }

    public void setStabile() {
        p = 40;
        setStatoEquilibrio();
        this.stabile = true;
        statoEquilibrio();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameWin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAvvia;
    private javax.swing.JButton buttonAvvia1;
    private javax.swing.JButton buttonStabile;
    private mls.FramePlot framePlot1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField textCodaCPU;
    private javax.swing.JTextField textCodaIO;
    private javax.swing.JFormattedTextField textGamma;
    private javax.swing.JTextField textGeneratoreArrivi;
    private javax.swing.JTextField textGeneratoreCentri;
    private javax.swing.JTextField textLimiteInferiore;
    private javax.swing.JTextField textLimiteSuperiore;
    private javax.swing.JTextPane textOutput;
    private javax.swing.JFormattedTextField textP;
    private javax.swing.JTextField textPuntoCentrale;
    private javax.swing.JFormattedTextField textTs;
    // End of variables declaration//GEN-END:variables
}
